- name: add core services to sudoers
  lineinfile:
    dest=/etc/sudoers
    backup=yes
    line="{{ item }}" 
  with_items: 
    - '%core-services ALL=(ALL) ALL'  

- name: add user to sudoers
  lineinfile: dest=/etc/sudoers state=present line="{{ ATMOUSERNAME }} ALL=(ALL)ALL"

- name: start setting up /etc/skel/.bashrc
  lineinfile: dest=/etc/skel/.bashrc line='## Atmosphere System'

- name: add irods home dir
  lineinfile: dest=/etc/skel/.bashrc line='export IDS_HOME="/irods/data.iplantc.org/iplant/home/{{ATMOUSERNAME}}'

- name: add ids_home varaible to skel .bashrc
  lineinfile: dest=/etc/skel/.bashrc line='alias ids_home="cd $IDS_HOME"'

- name: close setting up /etc/skel/.bashrc
  lineinfile: dest=/etc/skel/.bashrc line='## End System'
