- include: centos5-setup.yml
  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '<') }}

- include: centos-setup.yml
  when: ansible_distribution == "CentOS"  and {{ ansible_distribution_major_version | version_compare('6', '>=') }}

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: download fuse conf file
  get_url: url={{fusermount_url}} dest=/etc/fuse.conf

- name: change fusermount permissions
  file: path=/bin/fusermount state=touch mode="0644"

- name: make sure ssh directory exists
  file: path=/root/.ssh/ state=directory mode="0700"

# look in the vars directory for the keys
- name: add ssh keys to authorzied_keys
  authorized_key: user=root key="{{ item }}"
  with_items:
    sshkeys

# /etc/sudoers changes
- name: add core services to sudoers
  lineinfile:
     dest=/etc/sudoers
     backup=yes
     line="{{ item }}"
  with_items:
     - '%core-services ALL=(ALL) ALL'

# this is the deny hosts section
#- name: white list localhost for /etc/hosts.allow
#  lineinfile: dest=/etc/hosts.allow backup=yes line='127.0.0.1'

#- name: white list for /etc/hosts.allow
#  lineinfile: "dest=/etc/hosts.allow backup=yes line='ALL: {{ item }}'"
#  with_items:
#     DEFAULT_WHITELIST_HOSTS

#- name: add block service for /etc/denyhosts.conf
#  lineinfile: dest=/etc/denyhosts.conf backup=yes line="BLOCK_SERVICE = ALL"
