- name:  Copy over gateone debian package 
  copy: src=gateone-1.1-1.noarch.rpm dest=/tmp/gateone-1.1-1.noarch.rpm

- name: install python tornado 
  yum: name=python-tornado.noarch state=present

- name: install rpm
  yum: name=/tmp/gateone-1.1-1.noarch.rpm state=present

- name: start gateone service
  service: name=gateone state=restarted

- name: turn on chckonfig
  command: chkconfig --add gateone

