#
#- name: check if vdb exists, if not, bail
#  fail: msg="device vdb does not exist!"
#  when: "'vdb' in {{ ALL_DISKS }}"
#  tags: check_vdb

- name: verify that vbd is not already mounted on root
  fail: msg="vdb is mounted on root!"
  when: item.mount == '/' and item.device == '/dev/vdb'
  with_items: ansible_mounts
  tags: check_if_vdb_mounted_on_root

- name: mount /home unless it is already mounted
  mount: name={{ MOUNTNAME }} src={{ MOUNTSOURCE }} fstype={{ MOUNTTYPE }} state=mounted
  when: item.mount == "/home"
  with_items: ansible_mounts
  tags: mount_home

#- name: mount being passed by script
#  mount: name={{ MOUNTNAME }} src={{ MOUNTSOURCE }} fstype={{ MOUNTTYPE }} state=mounted

# TODO: create an /etc/fstab entry to mount 

###
#- include: template_ubuntu.yml
#  when: ansible_distribution == "Ubuntu"
#
#- include: template_CentOS5.yml
#  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '<') }}
#
#- include: template_CentOS.ym
#  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '>=') }}
###
