- name: mount being passed by script
  mount: name={{ MOUNTNAME }} src={{ MOUNTSOURCE }} fstype={{ MOUNTTYPE }} state=mounted

###
#- include: template_ubuntu.yml
#  when: ansible_distribution == "Ubuntu"
#
#- include: template_CentOS5.yml
#  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '<') }}
#
#- include: template_CentOS.yml
#  when: ansible_distribution == "CentOS" and {{ ansible_distribution_major_version | version_compare('6', '>=') }}
###
